[#ftl]
[@b.navbar title="权限管理"]
  [@b.navlist]
    [@b.navitem href="/security/index"]仪表盘[/@]
    [@b.navitem href="/security/nav/menu"]菜单管理[/@]
    [@b.navitem href="/security/authority/resource/search?orderBy=resource.name%20asc"]资源管理[/@]
    [@b.navitem href="/security/authority/field"]属性配置[/@]
    [@b.navitem href="/security/authority/permission"]权限配置[/@]
    [@b.navitem href="/security/my?nav=true" ]我的账户[/@]
  [/@]
[/@]