[#ftl]
[@b.head/]
[@b.toolbar title="数据限制域元信息配置"]bar.addBack("${b.text("action.back")}");[/@]
[#assign saveAction][#if dimension.persisted]!update?id=${dimension.id}[#else]!save[/#if][/#assign]
[@b.form action=saveAction theme="list"]
  [@b.textfield label="common.name" name="dimension.name" value="${dimension.name!}" required="true" maxlength="50"/]
  [@b.textfield label="标题" name="dimension.title" value="${dimension.title!}" required="true" maxlength="50"/]
  [@b.textfield  label="类型" name="dimension.typeName" value=dimension.typeName! required="true" style="width:300px"/]
  [@b.textfield label="关键字" name="dimension.keyName" value="${dimension.keyName!}" maxlength="50" style="width:50px"/]
  [@b.textfield label="其他属性" name="dimension.properties" value="${(dimension.properties)!}" style="width:300x;" maxlength="100" comment="多个属性用,分割"/]
  [@b.textarea label="数据源" name="dimension.source" value="${(dimension.source)!}" style="width:400px;" maxlength="6000" comment="基本类型，此处可以为空;使用json:/csv:"/]
  [@b.radios label="是否允许多值" name="dimension.multiple"  value=dimension.multiple/]
  [@b.select2 label="应用领域" name1st="domainId1st" name2nd="domainId2nd"
     items1st=domains items2nd= dimension.domains
     option="id,title"/]
  [@b.formfoot]
    [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit" /]
  [/@]
</table>
[/@]
[@b.foot/]
