[#ftl]
[@b.head/]
[@b.grid items=docs var="doc"]
  [@b.row]
    [@b.col width="5%" title="序号"]${doc_index+1}[/@]
    [@b.col width="40%" property="name" title="标题"][@b.a target="_blank" href="!info?id=${doc.id}"]${doc.name!}[/@][/@]
    [@b.col width="15%" property="app.title" title="应用"/]
    [@b.col width="10%" title="用户类别"][#list doc.userCategories as uc]${uc.name}[#if uc_has_next]&nbsp;[/#if][/#list][/@]
    [@b.col width="10%" property="uploadBy" title="上传人"]${doc.uploadBy.name}[/@]
    [@b.col width="15%" property="updatedAt" title="上传时间"]${doc.updatedAt?string("yy-MM-dd HH:mm")}[/@]
  [/@]
[/@]
[@b.foot/]
