[#ftl]
[@b.head/]
[@b.grid items=docs var="doc"]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="40%" property="name" title="标题"][@b.a target="_blank" href="!info?id=${doc.id}"]${doc.name!}[/@][/@]
    [@b.col width="15%" property="app.title" title="应用"/]
    [@b.col width="10%" property="userCategory.id" title="用户类别"]${doc.userCategory.name}[/@]
    [@b.col width="10%" property="uploadBy" title="上传人"]${doc.uploadBy.name}[/@]
    [@b.col width="15%" property="updatedAt" title="上传时间"]${doc.updatedAt?string("yy-MM-dd HH:mm")}[/@]
  [/@]
[/@]
[@b.foot/]
