[#macro display menu]
[#if menu.entry??]
    [@b.navlist  class="nav nav-pills"]
    [@b.navitem href=menu.entry.name target="main"]${menu.title}[/@]
    [/@]
[#else]
[@b.navlist class="nav nav-pills"]${menu.title}
[#list menu.children as m]
    [#if m.entry??]
    [@b.navitem href=m.entry.name target="main"]${m.title}[/@]
    [#else]
    [@display m/]
    [/#if]
[/#list]
[/@]
[/#if]
[/#macro]
