[#ftl]
[@b.head/]
[@b.toolbar title="新建数据源"]bar.addBack();[/@]
<style>form.listform label.title{width:120px;}</style>
[@b.tabs]
  [@b.form action="!save" theme="list"]
    [@b.textfield name="dataSourceCfg.name" label="名称" value="${dataSourceCfg.name!}" required="true" maxlength="200"/]
    [@b.textfield name="dataSourceCfg.url" label="URL" value="${dataSourceCfg.url!}" required="true" maxlength="200" style="width:300px;"/]
    [@b.textfield name="dataSourceCfg.driverClassName" label="DriverClassName" value="${dataSourceCfg.driverClassName!}" required="true" maxlength="200"/]
    [@b.textarea name="dataSourceCfg.remark" label="备注" value="${dataSourceCfg.remark!}" maxlength="200"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]