[@b.head/]
[#assign sessionCaption]在线记录 ${sessionInfoes?size}[/#assign]
[@b.grid items=sessionInfoes  var="s" caption=sessionCaption]
  [@b.row]
    [@b.boxcol/]
    [@b.col title="序号" width="5%"]${s_index+1}[/@]
    [@b.col title="用户名" width="15%" property="principal"/]
    [@b.col title="姓名" width="10%" property="description"/]
    [@b.col title="IP" width="17%" property="ip"/]
    [@b.col title="客户端" width="12%" property="agent"/]
    [@b.col title="操作系统" width="10%" property="os"/]
    [@b.col title="登录时间" width="13%" property="login_at"]${s.loginAt?string('yyyy-MM-dd HH:mm:ss')}[/@]
    [@b.col title="最后访问时间" width="13%" property="last_access_at"]${s.lastAccessAt?string('yyyy-MM-dd HH:mm:ss')}[/@]
  [/@]
[/@]
<br/>
[@b.foot/]
