[#ftl]
[@b.navbar title="权限管理"]
  [@b.navlist]
    [@b.navitem href="/security/auth/index"]仪表盘[/@]
    [@b.navitem href="/security/auth/field"]属性配置[/@]
    [@b.navitem href="/security/auth/permission"]权限配置[/@]
    [@b.navitem href="/security/account/my?nav=true"]我的账户[/@]
  [/@]
[/@]