[#ftl]
[@b.head/]
[@b.toolbar title="新增用户"]bar.addBack("${b.text("action.back")}");[/@]
[@b.messages/]
[@b.form name="userForm" action="!save" class="listform" theme="list"]
    [@b.textfield name="user.code" value="" style="width:200px;" required="true" maxlength="30"/]
    [@b.textfield name="user.name" title="姓名" value="" style="width:200px;" required="true" maxlength="50" /]
    [@b.select name="user.category.id" label="user.category.name" value=user.category! items=categories /]
    [@b.radios name="user.enabled" value=user.enabled items="1:action.activate,0:action.freeze"/]
    [@b.radios name="user.locked" value=user.locked items="1:锁定,0:解锁"/]
    [@b.password label="user.password" name="user.password" value="" maxlength="20"  required="true" showStrength="true"/]
    [@b.datepicker name="user.passwordExpiredOn" format="date"/]
    [@b.startend label="user.beginOn-endOn" name="user.beginOn,user.endOn" required="true,false" start=user.beginOn end=user.endOn format="date"/]
    [@b.textarea cols="50" rows="1" name="user.remark" value=user.remark! maxlength="50"/]
    [@b.formfoot][@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/][/@]
[/@]
[@b.foot/]